### ISSUE TITLE
Deploy the STAC API backend database

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/asf-stac#7]
# Overview

Deploy the `pgstac` database via AWS RDS.

# Tasks

- [x] Determine how to adapt `pgstac` to run in AWS RDS.
- [x] Deploy a Postgres database to AWS RDS via CloudFormation
- [x] #9

**Comment by jtherrmann** [comment]
Double-check that PostGIS must be installed manually before running the migrate script.

**Comment by jtherrmann** [comment]
(**TL;DR:** We can't use `pgstac` with a serverless database because Aurora serverless doesn't currently support newer versions of Postgres, but I'm preserving the deployment/connection steps for a serverless Postgres database below, in case they become useful in the future.)

Unfortunately a serverless database won't work for our purposes (as I'll explain below), but I did create the following CloudFormation template and successfully deployed a serverless database:

```yaml
Resources:
  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: StacApiBackend
      Engine: aurora-postgresql
      EngineMode: serverless
      MasterUsername: postgres
      MasterUserPassword: password
      Port: 5432
      VpcSecurityGroupIds:
        - !GetAtt DatabaseSecurityGroup.GroupId

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for the STAC API backend database'
      SecurityGroupIngress:
        - SourceSecurityGroupName: default
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
```

The database security group inbound rule allows connections from the `default` security group (the default VPC security group), so you can follow these steps to connect to the database:
* Create an EC2 instance in the same VPC as your database
* Make sure the instance has the `default` security group attached
* SSH into the instance, then run `PGDATABASE=StacApiBackend PGUSER=postgres PGPASSWORD=sandboxpass123 PGHOST=<host> PGPORT=5432 psql` where `<host>` is the database cluster Endpoint (obtained from the AWS Console).

However, when we attempt to run `pypgstac migrate` on our database from within our EC2 instance, the command fails with `Exception: PGStac requires PostgreSQL 13+`. We run `select version();` from `psql` and see that the database is running `PostgreSQL 10.18`. We can specify the version with the [`EngineVersion`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-engineversion) property of the database cluster, but when we check the available versions with:

```
aws rds describe-db-engine-versions --engine aurora-postgresql --query "DBEngineVersions[].EngineVersion" --filters Name=engine-mode,Values=serverless
```

we see that the only two supported versions are `10.18` and `11.13`. If we remove the `--filters` option, we see versions up to `14.5`. So it would appear that we cannot use `pgstac` with a serverless database, because serverless doesn't support Postgres 13+.
